# Generated by Django 3.2.4 on 2021-06-14 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tipo de Usuario')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre del tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('passwordUsuario', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.tipousuario')),
            ],
        ),
    ]
